# Generated by Django 4.2.16 on 2024-10-02 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed_by',
            new_name='complete_by',
        ),
    ]
